language: elixir
matrix:
  include:
    - otp_release: 22.2
      elixir: 1.10
env:
  global:
    - MIX_HOME=$HOME/.mix
cache:
  directories:
    - $HOME/.mix
    - deps
    - _build
before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository universe -y
  - sudo add-apt-repository ppa:certbot/certbot -y
  - sudo apt-get update
  - sudo apt-get install -y certbot
script:
  - mix compile --warnings-as-errors
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=prod mix compile --warnings-as-errors
  - mix test
  - mix format --check-formatted
  - mix dialyzer
